[package]
name = "wavetable"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.14.0"
libmath = "*"
crossterm = "0.26.1"
num = "0.4.0"
spmc = "0.3.0"
